fix: findHost and findHostHost should allow undefined lazyLoading config
ember-engines/ember-engines pull request #734
Opened 2020-10-21 05:28 UTC by xg-wang

Normally engine's parent is the project and the findHost loop stops at
the first level dependency engine. If an engine's parent is another
engine it's also fine. However if the parent is an addon that did not
specify lazyLoading the build breaks saying cannot read enabled of
undefined.  This change allows addon uses engines for its dummy app.

2020-10-21 11:38 UTC, rwjblue requested changes
Thanks for working on this! Made a couple small suggestions, but otherwise looks good to me!

2020-10-21 11:38 UTC, rwjblue commented on packages/ember-engines/lib/utils/ensure-lazy-loading-hash.js
> +    typeof context.lazyLoading === 'undefined'
I don't think we need `typeof` here for checking undefined, we can just compare:

```suggestion
    context.lazyLoading === undefined
```

2020-10-21 11:38 UTC, rwjblue commented on packages/ember-engines/lib/utils/ensure-lazy-loading-hash.js
> +      enabled: context.lazyLoading,
Let's make this a bit more explicit about always being a Boolean:

```suggestion
      enabled: Boolean(context.lazyLoading),
```

2020-10-21 14:36 UTC, rwjblue approved these changes

2020-10-21 15:14 UTC, xg-wang commented
lol forgot to update the test, I blame github apply suggestion too easy to use

2020-10-21 15:15 UTC, rwjblue commented
> lol forgot to update the test, I blame github apply suggestion too easy to use

HAHA! yes, I've been trolled by this before as well...

2020-10-21 19:04 UTC, merged

2020-10-22 01:04 UTC, xg-wang commented
@rwjblue can we get a release for this change?